# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 05:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidate', '0002_delete_candidate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('college_name', models.CharField(max_length=100)),
                ('year_of_passout', models.IntegerField(max_length=50)),
                ('exam_date', models.DateTimeField()),
            ],
        ),
    ]
