# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 05:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0004_question'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.AddField(
            model_name='candidate',
            name='code',
            field=models.FileField(null=True, upload_to='media/file', verbose_name='Code File'),
        ),
    ]
