# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 09:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0006_auto_20171026_0932'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='ques_no',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
